configure onboarding navigation
ffg-seva/visahoi pull request #178
Opened 2022-09-27 11:49 UTC by dvsilviyageo

Summary:
* Onboarding navigation can be configured to be either horizontal or vertical
* By default it is vertical.

Screenshots:
![image](https://user-images.githubusercontent.com/104566246/192517471-8ff1fa1e-929a-4d77-a451-165eef9e645e.png)
![image](https://user-images.githubusercontent.com/104566246/192517567-9f67c5d3-170c-4e0c-96b5-79d3e2c2793c.png)

2022-10-05 10:49 UTC, dvdanielamoitzi commented
Problem: the transition is not working for the horizontal layout @dvdanielamoitzi

2022-11-24 16:25 UTC, dvdanielamoitzi requested changes

2022-11-24 16:25 UTC, dvdanielamoitzi commented on packages/core/src/components/OnboardingNavigation.svelte
> +    /* bottom: 30px; */
```suggestion
```

2022-11-24 16:25 UTC, dvdanielamoitzi commented on packages/core/src/components/OnboardingNavigation.svelte
> +    /* flex-direction: row; horizontal */
```suggestion
```

2022-11-24 16:25 UTC, dvdanielamoitzi commented on packages/core/src/components/OnboardingNavigation.svelte
> +    /* transition: opacity 0.5s ease, right 0.5s ease; */
```suggestion
```

2022-11-24 16:25 UTC, dvdanielamoitzi commented on packages/core/src/components/OnboardingNavigation.svelte
> +    /* transition: opacity 0.5s ease, bottom 0.5s ease; */
```suggestion
```

2022-11-24 16:25 UTC, dvdanielamoitzi commented on packages/core/src/components/NavigationMarker.svelte
> +  /* .visahoi-marker-navigation-item {
you can remove this codeblock when it's commented out anyways

2022-11-24 16:44 UTC, dvdanielamoitzi commented
As already discussed, can you please position the "enter edit mode" btn like this?
![image](https://user-images.githubusercontent.com/57343176/203833743-2c16059a-c5ac-4e24-bc3f-ef6c91bbf517.png)

2022-11-28 09:51 UTC, dvdanielamoitzi commented
When I have the horizontal navigation, i can somehow click the "right" btn even if I already selected the first point (and the arrow btn is correctly disabled). But when I click it, it jumps to the previous marker (actually nothing at all should happen)

[Screencast from 2022-11-28 10:48:46.webm](https://user-images.githubusercontent.com/57343176/204247137-97f38ecd-b3a1-4036-af60-71e116193e54.webm)

2023-01-24 12:27 UTC, dvsilviyageo commented
This branch is outdated all the changes and in this branch is refracted and added to other branch 'sgeo/configurable-onboarding-navigation'

2023-01-26 09:18 UTC, dvsilviyageo commented
Fixed in #252

2023-01-26 09:18 UTC, closed without merging