Use visahoi ids for default messages and markers
ffg-seva/visahoi pull request #258
Opened 2023-01-26 11:51 UTC by dvsilviyageo

2023-01-27 07:40 UTC, dvdanielamoitzi requested changes
Generally, it looks good :+1: 
What is still missing, is the case when the user creates a new message (in onboarding.ts -> createBasicOnboardingMessage()): there we need to do the same for the newly created marker, and in createBasicOnboardingStage() for the newly created stage.

Additionally, as I just looked at this code again: Could you please refactor the function createBasicOnboardingMessage() in onboarding.ts to not take the message id as a parameter, but instead assign a new id to each message that gets created (just like for the marker id in the same function).

2023-01-30 12:33 UTC, dvsilviyageo commented
Refactored the createBasicOnboardingMessage() to assign a new id to each new messages. The user now no need to pass the id of the new message to be created

2023-01-31 08:44 UTC, dvdanielamoitzi approved these changes

2023-02-06 14:09 UTC, dvdanielamoitzi approved these changes

2023-02-06 14:10 UTC, merged